## This workflow does not (always) have access to secrets because it can be triggered by Dependabot, which prevents the use of secrets.
name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    if: ${{ startsWith(github.event.pull_request.head.ref, 'hotfix/') == false }}
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      actions: "write"
    steps:
      - name: Echo
        run: |
          echo "echo world"
