name: Close PR
on:
  pull_request:
    types:
      - closed

jobs:
  delete-pr-environment:
    name: Delete the PR environment
    if: ${{ startsWith(github.event.pull_request.head.ref, 'hotfix/') == false }}
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    env:
      KPT_VERSION: v1.0.0-beta.18
      KPT_DELETE_PR_IMAGE: europe-west4-docker.pkg.dev/shypple-dev/docker/kpt-functions/delete-pr:0.1.1
    steps:
      - name: Echo
        run: |
          echo "echo world"
