name: Create Hotfix Branch from Tag

on:
  push:
    tags:
      - "v*"

jobs:
  create_hotfix_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup Git
      #   run: |
      #     git config user.name "GitHub Actions"
      #     git config user.email "actions@github.com"

      # - name: Create hotfix branch
      #   run: |
      #     TAG_NAME=${GITHUB_REF#refs/tags/}
      #     HOTFIX_BRANCH_NAME="hotfix-base/${TAG_NAME}"
      #     git checkout -b "${HOTFIX_BRANCH_NAME}" "${TAG_NAME}"
      #     git push origin "${HOTFIX_BRANCH_NAME}"
