name: Hotfix Workflow

on:
  push:
    branches:
      - hotfix/*

jobs:
  verify_hotfix_branch:
    name: Verify Hotfix Branch
    runs-on: ubuntu-latest

    steps:
      - name: Check if branch was created from tag
        id: verify_tag
        run: |
          tag_name=$(echo "${{ github.ref }}" | sed -n 's/refs\/tags\///p')
          commit=$(git rev-parse HEAD)

          if ! git show-ref --tags | grep -q "refs/tags/${tag_name}\$"; then
            echo "ERROR: No tag found for this hotfix branch"
            exit 1
          fi

          tag_commit=$(git show-ref --verify --hash refs/tags/${tag_name})
          if ! git merge-base --is-ancestor "${tag_commit}" "${commit}"; then
            echo "ERROR: Hotfix branch was not created from the latest tag"
            exit 1
          fi

      - name: Create Hotfix Base branch from tag
        id: create_base_branch
        uses: actions/checkout@v2
        with:
          ref: "refs/tags/${{ steps.verify_tag.outputs.tag_name }}"
          run: |
            git checkout -b hotfix-base/${{ steps.verify_tag.outputs.tag_name }}
