name: Create Hotfix PR

on:
  push:
    branches:
      - "hotfix/*"

permissions:
  contents: write
  pull-requests: write

jobs:
  create_hotfix_pr:
    runs-on: ubuntu-latest
    env:
      HOTFIX_BASE_PREFIX: hotfix-base
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Create hotfix base branch and PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURRENT_BRANCH=$(git branch --show-current)
          HOTFIX_BASE_BRANCH="${HOTFIX_BASE_PREFIX}${CURRENT_BRANCH#hotfix}"
          LATEST_TAG=$(git describe --tags)
          LATEST_TAG=$(echo $LATEST_TAG | cut -d '-' -f 1)

          # Check if hotfix base branch exists, create if not
          if ! git show-ref --verify --quiet refs/heads/${HOTFIX_BASE_BRANCH}; then
            git checkout -b ${HOTFIX_BASE_BRANCH} ${LATEST_TAG}
            git push origin ${HOTFIX_BASE_BRANCH}
          fi

          # Switch back to the hotfix branch
          git checkout ${CURRENT_BRANCH}

          # Check if a PR already exists, create if not
          PR_EXISTS=$(gh pr list --base ${HOTFIX_BASE_BRANCH} --head ${CURRENT_BRANCH} --json state --jq 'length' | tr -d '\n' || echo "0")

          if [ "${PR_EXISTS}" == "0" ]; then
            gh pr create --base ${HOTFIX_BASE_BRANCH} --head ${CURRENT_BRANCH} --title "Hotfix PR: ${CURRENT_BRANCH}" --body "This is a hotfix PR. 
            Please review and merge the changes."
          fi
