name: Hotfix PR

on:
  push:
    branches:
      - 'hotfix/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the shypple-next repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Validate Branch
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          base_tag=$(git describe --tags --abbrev=0 --match "v*" $current_branch^ 2>/dev/null)
          echo "Current branch: $base_tag"
          if [ -z "$base_tag" ]
          then
            echo "Error: Hotfix branch not created from a tagged branch"
            exit 1
          fi
      - name: Create Hotfix Branch from Tag
        run: |
          git fetch --all --tags
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          base_tag=$(git describe --tags --abbrev=0 --match "v*" $current_branch^ 2>/dev/null)
          hotfix_base_branch="hotfix-base/$base_tag"
          echo "Hotfix base branch: $hotfix_base_branch"

          git checkout tags/$base_tag -b $hotfix_base_branch
          git push origin $hotfix_base_branch
      
      # - name: Create Pull Request
      #   run:
      #     echo "Create PR"
      #     gh pr create --title "Hotfix" --body "Hotfix" --base hotfix-base/v2.17.1 --head hotfix/2.17.1
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ secrets.PAT_TOKEN }}
      #     title: 'Hotfix'
      #     commit-message: 'Merge hotfix'
      #     # branch: create-pull-request/patch
      #     # base: hotfix-base/v2.17.1
      #     labels: 'hotfix'
      # # - name: Output Hotfix Branch
      # #   id: create-hotfix-branch
      # #   run: |
      # #     current_branch=$(git rev-parse --abbrev-ref HEAD)
      # #     base_tag=$(git describe --tags --abbrev=0 --match "v*" $current_branch^)
      # #     echo ::set-output name=hotfix-branch::hotfix/$base_tag
