name: Hotfix Workflow

on:
  push:
    branches:
      - hotfix/*

jobs:
  verify_hotfix_branch:
    name: Verify Hotfix Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Hotfix Branch
        uses: actions/checkout@v3

      - name: Print current branch
        run: echo "Current branch is ${{ github.ref }}"
